env:
  selected: dev
  excluded: []
src:
  name: /Users/wangsenyuan/git/work/
  suffix: java
dest:
  type: batch
  name: /tmp/maycur-batch
  ns-processor:
    old-ns: maycur
    new-ns: dev
  remove-copyright: true
  file-line-limit: 4000
  remove-comment: true

